export const countries = [
  { value: 'EG', en: 'Egypt', ar: 'مصر' },
  { value: 'SA', en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
  { value: 'AE', en: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' },
  { value: 'KW', en: 'Kuwait', ar: 'الكويت' },
  { value: 'QA', en: 'Qatar', ar: 'قطر' },
  { value: 'BH', en: 'Bahrain', ar: 'البحرين' },
  { value: 'OM', en: 'Oman', ar: 'عمان' },
  { value: 'JO', en: 'Jordan', ar: 'الأردن' },
  { value: 'LB', en: 'Lebanon', ar: 'لبنان' },
  { value: 'IQ', en: 'Iraq', ar: 'العراق' },
  { value: 'SY', en: 'Syria', ar: 'سوريا' },
  { value: 'PS', en: 'Palestine', ar: 'فلسطين' },
  { value: 'LY', en: 'Libya', ar: 'ليبيا' },
  { value: 'TN', en: 'Tunisia', ar: 'تونس' },
  { value: 'DZ', en: 'Algeria', ar: 'الجزائر' },
  { value: 'MA', en: 'Morocco', ar: 'المغرب' },
  { value: 'SD', en: 'Sudan', ar: 'السودان' },
  { value: 'YE', en: 'Yemen', ar: 'اليمن' },
  { value: 'US', en: 'United States', ar: 'الولايات المتحدة' },
  { value: 'GB', en: 'United Kingdom', ar: 'المملكة المتحدة' },
  { value: 'FR', en: 'France', ar: 'فرنسا' },
  { value: 'DE', en: 'Germany', ar: 'ألمانيا' },
  { value: 'IT', en: 'Italy', ar: 'إيطاليا' },
  { value: 'ES', en: 'Spain', ar: 'إسبانيا' },
  { value: 'TR', en: 'Turkey', ar: 'تركيا' },
  { value: 'CN', en: 'China', ar: 'الصين' },
  { value: 'JP', en: 'Japan', ar: 'اليابان' },
  { value: 'IN', en: 'India', ar: 'الهند' },
  { value: 'CA', en: 'Canada', ar: 'كندا' },
  { value: 'AU', en: 'Australia', ar: 'أستراليا' },
  { value: 'BR', en: 'Brazil', ar: 'البرازيل' },
  { value: 'RU', en: 'Russia', ar: 'روسيا' },
];
